### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by wst7** [wstreet/g6-subway-map#1]
npm run build报错

**Comment by wst7** [comment]
F:\www\g6-for-subway-map\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

ReferenceError: paths is not defined
    at Object.<anonymous> (F:\www\g6-for-subway-map\config\webpack.config.prod.js:11:10)
    at Module._compile (F:\www\g6-for-subway-map\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (F:\www\g6-for-subway-map\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (F:\www\g6-for-subway-map\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (F:\www\g6-for-subway-map\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at F:\www\g6-for-subway-map\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (F:\www\g6-for-subway-map\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at yargs.parse (F:\www\g6-for-subway-map\node_modules\webpack-cli\bin\cli.js:71:45)
    at Object.parse (F:\www\g6-for-subway-map\node_modules\yargs\yargs.js:567:18)
    at F:\www\g6-for-subway-map\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (F:\www\g6-for-subway-map\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (F:\www\g6-for-subway-map\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! g6-for-subway-map@1.0.0 build: `webpack --progress --colors --config config/webpack.config.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the g6-for-subway-map@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\x1c\AppData\Roaming\npm-cache\_logs\2019-12-05T13_23_15_548Z-debug.log
